### ISSUE TITLE
Improper use of arguments in cli

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#210]
As explained in the email I have sent Friday, our use of arguments is incorrect.
`--` should always contain the full-name of the argument (eg: --git)
`-` should be the short-name of the argument (eg: -g)

**Comment by bccrisan** [comment]
I have redesigned the whole arguments handling but I have continued to work on bcrisan branch.
I will patiently wait for it to be merged and after that I will apply the patch for this issue.

The patch can be found [here](https://gist.github.com/bccrisan/f4e1b783612d30e44eb8b5b8933752c2)
and can be applied with:
``` bash
git apply patch_name.ext
```

**Comment by mutterroland** [comment]
Added my modifications in #213 in click way of implementation.

**Comment by bccrisan** [comment]
After the merge the script keeps throwing this error:
```
C:\Users\bogdan.crisan\AppData\Local\Programs\Python\Python37-32\python.exe E:/bcrisan/repos/mozilla-releng/firefox-infra-changelog/issue-221/client.py
Traceback (most recent call last):
  File "E:/bcrisan/repos/mozilla-releng/firefox-infra-changelog/issue-221/client.py", line 105, in <module>
    cli()
  File "C:\Users\bogdan.crisan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bogdan.crisan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\bogdan.crisan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bogdan.crisan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'mercurial'
```
The issues seems to be very strange:
```Python
@click.option('-hg', '--mercurial', is_flag=True, flag_value='mercurial',
              help='Run only for HG repos')
```
Apparently the `--mercurial` and `flag_value='mercurial'` need to be the same??
After I changed that locally it worked fine.
Same for the `--manual` and `flag_value='manual'`

**Comment by Akhliskun** [comment]
This issue acted really strange, as it was an intermittent for some reason.
In any case, it was fixed by #240
